### ISSUE TITLE
Loading progress indicator?

### ISSUE THREAD

**Issue by chrismclarke** [stats4sd/statistics-games#6]
Might be nice to have while generating large n trials. Example here:
http://www.excel-easy.com/vba/examples/progress-indicator.html

**Comment by dannyparsons** [comment]
On my machine Excel goes white with [Not responding] while it's generating large n. A progress bar or something to show that it hasn't crashed would be nice, but don't think this is urgent for before the workshop.

**Comment by dannyparsons** [comment]
Actually this only happens if I click in Excel while it's running. Otherwise I just get the waiting wheel which is ok.

**Comment by chrismclarke** [comment]
I looked into adding a progress indicator but in order to update the interface you have to allow excel to periodically pause the function calculation (via doevents) which seems to more than double the time required, so really not worth it. closing
